# Placeholders to be rewritten by launch file:
# - <entity> : Should be replaced by entity name: For example "robot".
# - <world> : Gazebo World name

# Odom
- ros_topic_name: "odom"
  gz_topic_name: "/model/<entity>/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# TF
- ros_topic_name: "tf"
  gz_topic_name: "/model/<entity>/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# TF
- ros_topic_name: "tf"
  gz_topic_name: "/model/<entity>/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# Joint State
- ros_topic_name: "joint_states"
  gz_topic_name: "world/<world>/model/<entity>/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# Cmd vel
- ros_topic_name: "cmd_vel"
  gz_topic_name: "/model/<entity>/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# Lidar
- ros_topic_name: "scan"
  gz_topic_name: "/world/<world>/model/<entity>/link/base_link/sensor/gpu_lidar/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera_os30a/image_raw"
  gz_topic_name: "/world/<world>/model/<entity>/link/base_link/sensor/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera_os30a/depth_image"
  gz_topic_name: "/world/<world>/model/<entity>/link/base_link/sensor/camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera_os30a/camera_info"
  gz_topic_name: "/world/<world>/model/<entity>/link/base_link/sensor/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera_os30a/points"
  gz_topic_name: "/world/<world>/model/<entity>/link/base_link/sensor/camera_aux/depth_image/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

# Servo joints
- ros_topic_name: "/servo_conn1_joint/cmd_pos"
  gz_topic_name: "/model/<entity>/joint/servo_conn1_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/servo_conn2_joint/cmd_pos"
  gz_topic_name: "/model/<entity>/joint/servo_conn2_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ